- name: .zshenv存在チェック
  stat: path={{ ANSIBLE_NODEBREW_NODEBREW_USER_HOME }}/.zshenv
  register: is_file
  sudo_user: "{{ ANSIBLE_NODEBREW_NODEBREW_USER }}"
  changed_when: false 
  always_run: yes

- name: .zshenv作成
  file: path={{ ANSIBLE_NODEBREW_NODEBREW_USER_HOME }}/.zshenv state=touch owner={{ ANSIBLE_NODEBREW_NODEBREW_USER }}  mode=0755
  sudo_user: "{{ ANSIBLE_NODEBREW_NODEBREW_USER }}"
  when: is_file.stat.md5 is not defined

- name: .zshenv_permission設定
  file: path={{ ANSIBLE_NODEBREW_NODEBREW_USER_HOME }}/.zshenv state=file owner={{ ANSIBLE_NODEBREW_NODEBREW_USER }}  mode=0755
  sudo_user: "{{ ANSIBLE_NODEBREW_NODEBREW_USER }}"
  when: is_file.stat.md5 is defined

- name: .zshenvでprofile.d/nodebrew.shを読み込むように変更
  lineinfile: line='source {{ ANSIBLE_NODEBREW_NODEBREW_USER_HOME }}/profile.d/nodebrew.sh' dest={{ ANSIBLE_NODEBREW_NODEBREW_USER_HOME }}/.zshenv insertafter=EOF
  sudo_user: "{{ ANSIBLE_NODEBREW_NODEBREW_USER }}"

